### ISSUE TITLE
Camera Intrinsics using realsense-ros

### ISSUE THREAD

**Issue by LuisC18** [OSU-AIMS/tic-tac-toe#12]
## Goal: 
Utilize camera intrinsics to make code more robust and adaptable to different environments, specifically different heights for the tictactoe board surface. 
## Issue: 
The introduction of the mh5l pedestal in the lab increased the urgency of this issue. Hardcoded values for contour area detection and pixel to cm scalars have been thrown off now that the mh5l is not attached to the table. The realsense-ros camera_launch we are using [here](https://github.com/OSU-AIMS/tic-tac-toe/blob/3f0006da17343ed681306faecdd96acfb067ff52/launch/board_tf_publisher.launch#L5) produces the /camera/depth/[camera_info](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/CameraInfo.html) topic which provides a intrinsic camera matrix in the form of:
```
    [fx  0 cx]
K = [ 0 fy cy]
    [ 0  0  1]
```
I looked at the output of K for our Realsense d435i.

**/camera/color/camera_info:**
```
[603.486572265625, 0.0, 318.92755126953125,
0.0, 603.2389526367188, 240.99517822265625,
0.0, 0.0, 1.0]
```
**/camera/depth/camera_info:**
```
[381.5738525390625, 0.0, 319.6754150390625,
0.0, 381.5738525390625, 239.91372680664062,
0.0, 0.0, 1.0]
```
I am not sure if the discrepancy between the color and depth topic is an issue, there is also a /camera/aligned_depth_to_color/camera_info which matches the color one above.

Found very similar [issue](https://github.com/IntelRealSense/realsense-ros/issues/709) which pointed me towards [librealsense](https://github.com/IntelRealSense/librealsense/wiki/Projection-in-RealSense-SDK-2.0) math explanation of projection. Within the pyrealsense2 module there is a [deprojection function](https://github.com/IntelRealSense/librealsense/blob/5e73f7bb906a3cbec8ae43e888f182cc56c18692/include/librealsense2/rsutil.h#L46) which @acbuynak has used in python before in his [realsense_vision_tools.py](https://github.com/OSU-AIMS/maze-runner/blob/e9f5340acba3439da6dc70ba3f6a9de5c736edd3/scripts/realsense_vision_tools.py#L397). I am unsure how to obtain the depth value parameter for the *rs2_deproject_pixel_to_point* function.

**Comment by acbuynak** [comment]
@adnanreddy  Can you help out with this? It aligns with your current project statement. Thanks!

**Comment by AdamExley** [comment]
## Intrinsics

This is gone over in the librealsense docs you linked but I wanted to emphasize:

> fx and fy are the focal length of the camera's width and height --  Essentially how 'zoomed in' the camera is.
> ppx and ppy specify the origin of the camera's view. These tell you where the origin of the camera is. 

>**Example**
>If ppx and ppy are 320, 240;
>Any object at pixel (240,320) will be at XY = (0,0) relative to the camera. 
>The Z value of this pixel is just the actual depth. 

**fx, fy, ppx, and ppy are properties of each camera.**
The depth and color cameras are different cameras: they have different intrinsics.
The aligned depth stream is the depth stream distorted to have the same intrinsics as the color stream.

**Use the aligned depth stream and just use color intrinsics, it'll make everything easier**

## Deprojection

From my recollection *rs2_deproject_pixel_to_point* takes pixel position, intrinsics, and depth.
@LuisC18 *This depth is just the depth value of the pixel in meters;* if you have a depth array of the image, just index into the pixel you want to get it's depth. Pass that to the function.

**Comment by LuisC18** [comment]
Simple implementation of cameraInfo topic use and depth seen in [toolbox_depth_vision.py](https://github.com/OSU-AIMS/tic-tac-toe/blob/TheGame/scripts/toolbox_depth_vision.py).

Issue closed due to TTT not utilizing depth.
