### ISSUE TITLE
Learning how to use Tesseract

### ISSUE THREAD

**Issue by MohammadKhan-3** [OSU-AIMS/tic-tac-toe#4]
### GOAL: 
- Learning about Tesseract to know whether it's useful for creating constrained motion paths for complex motions (ie: painting, welding, reducing extraneous motions during pick&place)
- If Tesseract is not ideal, what can be done otherwise?
______________________
### Background: 

- Installed properly --> how to use it based on documentation provided & our experience

List of tutorials/documentation found: (note: Tesseract is still heavily under development, so proper tutorials & documentation are sparse)
- ROS Tesseract documentation: https://tesseract-docs.readthedocs.io/en/latest/_source/intro/tesseract_setup_wizard_doc.html
- ROS Tesseract Setup Wizard: https://www.youtube.com/watch?v=tC8iIiECIGY&t=2s
- ROS Tesseract Wiki: https://ros-industrial-tesseract.readthedocs.io/en/latest/ & https://tesseract-docs.readthedocs.io/en/latest/index.html

**Comment by MohammadKhan-3** [comment]
Able to use Tesseract Setup Wizard easily
- Outputs a SRDF file --> how can we use this for planning robot motion?

Also there aren't many tutorials or examples on using Tesseract for a specific robot motion. It's not well documented as MoveIt

## Next Steps: 
- Search for more Tesseract Documentation and examples
- Look into moveIt and how to constraint joint motion 
### **Start here:** 
- Jeroen Elion GitHub: https://github.com/JeroenDM/elion
- GSoC: Motion planning with general end-effector constraints in MoveIt: https://github.com/ros-planning/moveit/issues/2092
- A new approach for planning with path constraints in MoveIt: https://moveit.ros.org/moveit/2020/09/10/ompl-constrained-planning-gsoc.html
-  Planning with Approximated Constraint Manifolds
http://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/planning_with_approximated_constraint_manifolds/planning_with_approximated_constraint_manifolds_tutorial.html
- Log for Cartesian motion planning with constraints in MoveIt: 
https://docs.google.com/document/d/1PxItLhBOdmTKrARTYpf57xNYrKbn2MC0qXPK_ZEOpMc/edit#heading=h.d65w53yf9hcl
- Ros Industrial Tesseract Setup Wizard: https://rosindustrial.org/news/2020/9/19/tesseract-setup-wizard-leveraging-ignition

**Comment by MohammadKhan-3** [comment]
Majority of the code is in C++. So I'll need to learn enough C++ to understand Tesseract and other MoveIt constraints used. 
- This will be put on hold until enough C++ is learned. But I think the project is still worth pursuing. 

Having motion path constraints can improve accuracy and reduce the extraneous motion paths the robot sometimes does. Motion path constraints are important for applications such as painting and welding where you want no extraneous motion that would ruin the job.

### Next Steps: 
- Learn enough C++ to understand the code & add comments to this code https://github.com/JeroenDM/elion
- Side Project: Create nodes & topics to communicate between python ad C++ scripts for future projects

**Comment by MohammadKhan-3** [comment]
Article on Tesseract: 
- 
- https://rosindustrial.org/news/2020/8/4/real-time-trajectory-planning-for-industrial-robots
### Next Steps: 
https://github.com/ros-industrial-consortium/tesseract_ros/blob/master/tesseract_ros_examples/src/pick_and_place_example.cpp
Will start git-clone this repo & dissect the code to see how the pick & place works.

**Comment by LuisC18** [comment]
### Issue:
Cannot load custom urdf/xacro files in tesseract-ignition. The wizard only recognizes files ending in .urdf, meaning any xacro files are not seen. Changing the .xacro file extension to .urdf resulted in the following error:

```
Error:   Error parsing urdf, no links were found for urdf 'robot_mh5l_pgn64_table'! 
at line 165 in /root/parts/tesseract-workspace/build/src/tesseract/tesseract/tesseract_urdf/src/urdf_parser.cpp

Error:   Failed to parse URDF.
at line 184 in /root/parts/tesseract-workspace/build/src/tesseract/tesseract/tesseract/src/tesseract.cpp
[GUI] [Err] [tesseract_setup_wizard.cpp:135] Failed to parse URDF/SRDF!
```

**Comment by acbuynak** [comment]
Closing as no longer a focus of this project.
