### ISSUE TITLE
Realsense frame grab is very dark

### ISSUE THREAD

**Issue by LuisC18** [OSU-AIMS/tic-tac-toe#5]
We believe the issue is because the camera does not have time to adjust to lighting before grabbing a color frame. Our realsense pipeline is initialized in [realsense_tools.py](https://github.com/OSU-AIMS/tic-tac-toe/blob/TheGame/game_scripts/Realsense_tools.py)

![colordark](https://user-images.githubusercontent.com/75920339/127530796-c2a8bd60-bf41-45e1-b055-7ce913e64e4f.jpg)

**Comment by LuisC18** [comment]
Tried @acbuynak [realsense_vision_tools.py](https://github.com/OSU-AIMS/maze-runner/blob/melodic/scripts/realsense_vision_tools.py) which outputted the correct lighting but inverted colors.

![colorx](https://user-images.githubusercontent.com/75920339/127531083-1d4103a6-ae6e-4e5f-ad10-65be22ba928e.jpg)

**Comment by acbuynak** [comment]
The coloring issue looks like a data type format issue. The output system is expecting data type `rgb8` but it is being given `rbg8`. Thus, the colors are flipped. 

Reference: https://github.com/OSU-AIMS/realsense-capture-tool/commit/d26c001c5444473e30274f8cc39c535754e75d9a

The under exposed issue may be resolvable by just adding a short `time.wait(3000)` to give the camera time to boot up and automatically set the exposure.

**Comment by acbuynak** [comment]
Is this resolved?
